index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: [GET]
contact_us:
    path: /contact_us
    controller: App\Controller\ContactUsController::index
    methods: [GET]
greeflas_newsletter:
    resource: '@GreeflasNewsletterBundle/Resources/config/routes.yaml'