index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: [GET]
contact_us:
    path: /contact_us
    controller: App\Controller\ContactUsController::index
    methods: [GET]
greeflas_newsletter:
    resource: '@GreeflasNewsletterBundle/Resources/config/routes.yaml'
post:
    path: /news/{id}
    controller: App\Controller\PostController::index
    methods: [GET]
category:
    path: /category/{id}
    controller: App\Controller\PostController::categoryPosts
    methods: [GET]